name: Android CI

on:
  push:
    branches:
      - delivery

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: Run checks
        run: ./gradlew detekt assembleDebug testDebugUnitTest \
          --no-daemon \
          --parallel \
          --build-cache \
          --stacktrace